def archetypes_mapper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("archetypes-mapper", kwargs)


def weather_helper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("weather-helper", kwargs)


def surroundings_helper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("surroundings-helper", kwargs)


def terrain_helper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("terrain-helper", kwargs)


def streets_helper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("streets-helper", kwargs)


def radiation(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("radiation", kwargs)


def schedule_maker(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("schedule-maker", kwargs)


def demand(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("demand", kwargs)


def emissions(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("emissions", kwargs)


def system_costs(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("system-costs", kwargs)


def shallow_geothermal_potential(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("shallow-geothermal-potential", kwargs)


def water_body_potential(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("water-body-potential", kwargs)


def photovoltaic_thermal(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("photovoltaic-thermal", kwargs)


def photovoltaic(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("photovoltaic", kwargs)


def sewage_potential(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("sewage-potential", kwargs)


def solar_collector(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("solar-collector", kwargs)


def network_layout(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("network-layout", kwargs)


def thermal_network(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("thermal-network", kwargs)


def thermal_network_optimization(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("thermal-network-optimization", kwargs)


def decentralized(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("decentralized", kwargs)


def optimization(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("optimization", kwargs)


def dbf_to_excel_to_dbf(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("dbf-to-excel-to-dbf", kwargs)


def data_initializer(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("data-initializer", kwargs)


def database_migrator(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("database-migrator", kwargs)


def create_new_scenario(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("create-new-scenario", kwargs)


def rename_building(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("rename-building", kwargs)


def create_mixed_use_type(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("create-mixed-use-type", kwargs)


def test(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("test", kwargs)


def run_unit_tests(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("run-unit-tests", kwargs)


def run_all_plots(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("run-all-plots", kwargs)


def multi_criteria_analysis(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("multi-criteria-analysis", kwargs)


def zone_helper(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("zone-helper", kwargs)


def plots(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("plots", kwargs)


def compile(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("compile", kwargs)


def dashboard(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("dashboard", kwargs)


def excel_to_shapefile(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("excel-to-shapefile", kwargs)


def extract_reference_case(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("extract-reference-case", kwargs)


def list_demand_graphs_fields(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("list-demand-graphs-fields", kwargs)


def shapefile_to_excel(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("shapefile-to-excel", kwargs)


def trace_inputlocator(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("trace-inputlocator", kwargs)


def workflow(kwargs):
    """NOTE: this whole file is autogenerated"""
    import cea_runner    
    cea_runner.run("workflow", kwargs)

