def SCRIPT_PY_NAME(kwargs):
    """NOTE: this whole file is autogenerated"""
    if kwargs["start"]:
        import cea_runner    
        cea_runner.run("SCRIPT_NAME", {k:v for k, v in kwargs.items() if k != "start"})
    return kwargs["start"]

